---
output:
  pdf_document: default
  html_document: default
---

```{python eval=TRUE,echo=FALSE}
# SOLUCAO PARA CORRIGIR PROBLEMA COM PLOT DO PYTHON
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/ProgramData/Anaconda3/Library/plugins/platforms'
```


# Visualização e Análise gráfica na Ciência de dados {#capitulo-3}
O capítulo  \@ref(capitulo-2) apresenta a tabela como uma forma poderosa para estruturar e visualizar informações. No entanto, quando trabalhamos com enormes tabelas com uma imensa quantidade de linhas e colunas se torna difícil interpretar suas informações, não importa o quão organizadas elas estejam. Às vezes, é muito mais fácil interpretar essas informações através de gráficos, conteúdo que será explorado no decorrer deste capítulo.

A construção e visualização gráfica é de extrema importância na área de ciência de dados, pois é a partir de um bom gráfico que se torna possível extrair ideias, hipóteses ou até conclusões a respeito de um tema. A importância desse tipo de análise pode ser expressa por um ditado popular bastante conhecido: "Uma imagem vale por mil palavras".

Para demonstrar os diferentes tipos de gráficos que você pode encontrar nesta área, serão utilizadas duas bases de dados primordiais para exemplificar os conceitos deste capítulo: os microdados do Exame Nacional do Ensino Médio (ENEM) de 2018 para os estudantes da cidade de Salvador (Bahia) e diversas informações sobre o turismo na capital bahiana. Os microdados do ENEM são publicados pelo Instituto Nacional de Estudos e Pesquisas Educacionais Anísio Teixeira (INEP) em seu site. Já as informações sobre o turismo advém de diversas fontes ligadas ao governo do estado da Bahia, mais precisamente a Secretaria de Turismo do Estado da Bahia (SETUR).

```{python eval=TRUE,echo=FALSE}
# Modulos usados
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Carregar bases de dados processadas capitulo
dados_enem_alunos = pd.read_csv('data/dados_educacao_enem2018_alunosSalvadorInfo.csv')
dados_enem_notas = pd.read_csv('data/dados_educacao_enem2018_notasSalvadorMaxMin.csv')
dados_turismo_fluxoGeralSSA = pd.read_csv('data/dados_turismo_fluxoTuristicoSalvador2011-2016.csv')
dados_turismo_fluxoRodoviariaSSA = pd.read_csv('data/dados_turismo_fluxoRodoviariaSalvador2019.csv')
```

```{python eval=TRUE,echo=FALSE}
# FUNCAO - Fazer anotação dos valores com frequencia absoluta em graficos de barras
def fazer_anotacao_frequencia_absoluta(eixo, coord_texto_xy):
    # Loop em cada barra que existe no gráfico
    for barra in eixo.patches:
        tamanho_barra = barra.get_width() # Pegar o tamanho da barra
        texto_barra = tamanho_barra # Texto que sera anotado referente a barra
        coord_anotacao_xy = (barra.get_x() + tamanho_barra, barra.get_y()) # Coordenada de onde sera a anotacao no grafico
        eixo.annotate(texto_barra, coord_anotacao_xy, xytext=coord_texto_xy, fontsize=15, color='black',
                    textcoords='offset points', horizontalalignment='right')

# FUNCAO - Fazer anotação dos valores com frequencia relativa em graficos de barras                   
def fazer_anotacao_frequencia_relativa(eixo, coord_texto_xy, total_amostras):
    # Loop em cada barra que existe no gráfico
    for barra in eixo.patches:
        tamanho_barra = barra.get_width()  # Pegar o tamanho da barra
        texto_barra = str(round(100*tamanho_barra/total_amostras, 2)) + ' %' # Texto que sera anotado referente a barra
        coord_anotacao_xy = (barra.get_x() + tamanho_barra, barra.get_y())
        eixo.annotate(texto_barra, coord_anotacao_xy, xytext=coord_texto_xy, fontsize=15, color='black', 
                      textcoords='offset points', horizontalalignment='right')
        
```

## Gráfico de barra
O **Gráfico de barras** é uma forma bastante comum de visualização na área de ciência de dados sendo bastante utilizado para expressar noções de variáveis categóricas. 

Seguindo uma definição mais formal, trata-se da exibição de barras, igualmente espaçadas e largas, para cada categoria. O comprimento, ou seja, o tamanho de cada barra será proporcional à **frequência** desta categoria. Será através da interpretação das frequências dispostas que perguntas como "qual a categoria mais dominante desta variável?" ou "qual categoria apresenta uma menor quantidade?" podem ser respondidas. Como exemplo é apresentado o gráfico abaixo:

```{python fig31, fig.cap='Distinção de estudantes por cor/raça da cidade de Salvador inscritos no ENEM 2018', out.width='90%', fig.asp=.75, fig.align='center', echo=FALSE}
# Definir tamanho da figura
plt.figure(figsize=(20,10));

# Realizar grafico
eixo = sns.countplot(y='TP_COR_RACA', data=dados_enem_alunos, palette=sns.color_palette("Set2"));
plt.yticks(fontsize=25);
plt.xticks(fontsize=25);
plt.xlabel('Quantidade de alunos', fontsize=30, weight = 'bold');
plt.ylabel('Categorias', fontsize=30, weight = 'bold');
eixo.spines['right'].set_visible(False);
eixo.spines['top'].set_visible(False);
fazer_anotacao_frequencia_absoluta(eixo, (55, -45));
plt.tight_layout();
plt.show();
```

A `fig31` apresenta a distinção de estudantes por cor/raça inscritos no ENEM 2018 na cidade de Salvador (BA), onde os valores a direita das barras indicam a quantidade de alunos pertencentes aquela categoria. Através da análise deste gráfico é possível responder as perguntas apresentadas anteriormente como:
- "Qual a categoria mais dominante nesta variável?" A categoria `Parda` domina em maior quantidade. Ou seja, em Salvador existem mais estudantes auto declarados pardos.
- "Qual a categoria apresenta uma menor quantidade?" A categoria `Indígena` apresenta uma baixa representatividade.

Note como uma visualização gráfica é melhor em comparação a uma tabela para a mesma informação:

```{python eval=TRUE,echo=FALSE}
dados_enem_alunos['TP_COR_RACA'].head(100)
```

Ao invés do trabalho repetitivo de contar na tabela quantos estudantes estão em cada categoria, através de uma linguagem de programação com alguns comandos isso é realizado de forma automática!

Apesar do gráfico anterior apresentar informações interessantes, sua construção pode ser aprimorada ainda mais e é isso o que a figura seguinte irá trazer:

```{python fig32, fig.cap='Distinção de estudantes por cor/raça da cidade de Salvador inscritos no ENEM 2018 ordenados.', out.width='90%', fig.asp=.75, fig.align='center', echo=FALSE}
# Definir tamanho da figura
plt.figure(figsize=(20,10));

# Realizar grafico
eixo = sns.countplot(y='TP_COR_RACA', data=dados_enem_alunos, palette=sns.color_palette("Set2"), order = dados_enem_alunos['TP_COR_RACA'].value_counts().index);
plt.yticks(fontsize=25);
plt.xticks(fontsize=25);
plt.xlabel('Quantidade de alunos', fontsize=30, weight = 'bold');
plt.ylabel('Categorias', fontsize=30, weight = 'bold');
eixo.spines['right'].set_visible(False);
eixo.spines['top'].set_visible(False);
fazer_anotacao_frequencia_absoluta(eixo, (55, -45));
plt.tight_layout();
plt.show();
```

Note como a `fig32` deixa mais claro outra informação subjetiva: ordem. Com as barras ordenadas, fica mais fácil para o leitor verificar em ordem crescente (do menor para o maior) ou decrescente (do maior para o menor) como está distribuída as categorias naquela variável. Fica mais simples e direto verificar, por exemplo, que a quantidade de estudantes **Não declarado** é significamente menor que estudantes na categoria `Pardo` ou `Preta`. 

É importante ressaltar que até o momento foi trabalho apenas com valores absolutos, ou seja, a quantidade total que aquela categoria apareceu naquela variável. Isso é chamado comumente de **frequência absoluta** (FA). Existe outra forma de dispor esses mesmos valores através da **frequência relativa** (FR). A frequência relativa é definida como uma proporção dada por:
$$FR = {FA \choose T}$$
Onde $T$ é o tamanho amostral e $FA$ a frequência absoluta. Porém é comum apresenta-la no formato $FR (\%)$ onde "%" indica porcentagem, ou seja, parcela de um todo. Para conseguir essa nova visualização, altera-se a proporção anterior da seguinte forma:
$$FR (\%) = 100*{FA \choose T}$$
A análise utilizando a frequência relativa é bastante usada em pesquisas, pois torna a comparação mais significante. Transformando a `fig32` de FA para FR obtém-se:

```{python fig33, fig.cap='Distinção de estudantes por cor/raça da cidade de Salvador inscritos no ENEM 2018 ordenado em frequência relativa.', out.width='90%', fig.asp=.75, fig.align='center', echo=FALSE}
# Definir tamanho da figura
plt.figure(figsize=(20,10));

# Realizar grafico
eixo = sns.countplot(y='TP_COR_RACA', data=dados_enem_alunos, palette=sns.color_palette("Set2"), order = dados_enem_alunos['TP_COR_RACA'].value_counts().index);
plt.yticks(fontsize=25);
plt.xticks(fontsize=25);
plt.xlabel('Quantidade de alunos', fontsize=30, weight = 'bold');
plt.ylabel('Categorias', fontsize=30, weight = 'bold');
eixo.spines['right'].set_visible(False);
eixo.spines['top'].set_visible(False);
fazer_anotacao_frequencia_relativa(eixo, (65, -45), len(dados_enem_alunos));
plt.tight_layout();
plt.show();
```

Ao analisar a `fig33` você pode perguntar "Qual é o impacto/diferença em usar FA ou FR?" ou "O que eu ganho realizando minha análise com FR?". Talvez uma análise comparativa entre `fig32` e `fig33` possa auxiliar na resolução dessas questões:
- Ao analisar a `fig33` você identificar que mais de 80% dos estudantes inscritos no ENEM 2018 são da categoria `Pardo` ou `Preta`, verificado ao somar as $FR(\%)$.
- A quantidade de estudantes "Não declarado" é maior do que a quantidade somada de estudantes declarados como `Indígena` ou `Amarela`.

Essa informações expressivas de quantidades não poderiam ser verificadas na `fig32` visto que não fica claro o tamanho amostral na $FA$, apenas na $FR(\%)$.Toda essa análise mostra como um gráfico pode ser aperfeiçoado com o tempo e como um gráfico de barras pode conter tantas informações. Vale ressaltar que inclusive essa predominância de pessoas auto declaradas de cor `Parda` ou `Preta` reflete a realidade da capital mais negra do Brasil segundo o censo de 2018 do Instituto Brasileiro de Geografia e Estatística (IBGE).

Apesar do gráfico de barras estar bastante relacionado com variáveis categóricas, ele pode ser usado também para expressar grandezas numéricas de uma forma visual. Isso é realizado na imagem seguinte:
```{python fig34, fig.cap='Notas máximas e mínimas no ENEM 2018 para os estudantes de Salvador (BA).', out.width='90%', fig.asp=.75, fig.align='center', echo=FALSE}
plt.figure(figsize=(20,10));
eixo = sns.barplot(y='Materia',x='Nota',hue='Tipo',data=dados_enem_notas, palette=sns.color_palette("Set2"));
fazer_anotacao_frequencia_absoluta(eixo, (50,-30));
plt.show();
```

A `fig34` apesar de não apresentar variáveis com nenhum teor categórico, pois as notas de provas apresentam um caráter numérico, demonstra a utilização do gráfico de barras para demonstrar a discrepância entre as maiores e menores notas para as diversas provas do ENEM (desconsiderando provas zeradas). A utilização deste tipo de gráfico com esse viés é interessante para ressaltar diferenças principalmente em resultados, fazendo com que o leitor perceba como um valor é superior ou inferior que o outro.

## Gráfico de pizza

O **Gráfico de pizza**, também conhecido como gráfico de setores, pode ser visto como uma forma alternativa ao **gráfico de barras** para expressar informações . Neste gráfico, construído exclusivamente para variáveis categóricas, cada fatia referente a uma categoria possui um tamanho proporcional a $FR(\%)$ . Abaixo é apresentado um exemplo desta modalidade:
```{python fig35, fig.cap='Quantidade de alunos do sexo masculino e feminino inscritos no ENEM 2018.', out.width='90%', fig.asp=.75, fig.align='center', echo=FALSE}
# Construcao de um gráfico de pizza em python
categorias = ['Masculino', 'Feminino'];
qtd_de_amostras_categorias = [dados_enem_alunos['TP_SEXO'].value_counts()[1], dados_enem_alunos['TP_SEXO'].value_counts()[0]];
figura, eixo = plt.subplots();
eixo.pie(qtd_de_amostras_categorias, labels=categorias, autopct='%1.1f%%', shadow=False);
eixo.axis('equal');
plt.show();
```

Através da análise da `fig35` é possível identificar que a proporção de estudantes do sexo feminino é maior do que do sexo masculino. Isso é verificado pelo tamanho da $FR(\%)$ e também pela "fatia" dessa categoria. Neste tipo de gráfico, a categoria mais dominante irá apresentar um tamanho maior em comparação as demais, caso isso não ocorra provavelmente existe alguma coisa errada com seu gráfico.

A análise utilizando um gráfico de pizza é interessante quando é estudado uma variável categórica em específico e almeja apresentar possíveis dominâncias entre suas classes. Essa abordagem, todavia, não é recomendado quando o atributo estudado apresenta muitas categorias, pois a visualização se torna mais difícil para o leitor. Neste caso é recomendado a utilização dos gráficos de barras.

## Gráficos de Dispersão

## Séries temporais
A **série temporal**, comumente chamada de gráfico de linha, se trata de uma coleção de observações realizadas ao longo do tempo. Por se tratar de uma coleta sequencial, ou seja, feita uma após a outra torna o fator de ordenação fundamental: importa saber se determinada observação ocorreu antes ou depois de determinado evento. Um exemplo muito conhecido deste tipo de gráfico, presente no dia a dia do leitor é a previsão do tempo em jornais: lhe é apresentado as previsões para o dia presente e alguns dias futuros da semana. Outro exemplo dessa análise é apresentado abaixo:

``` {python fig36, fig.cap='Fluxo turístico na capital da Bahia nos anos de 2011 até 2016.', out.width='90%', fig.asp=.75, fig.align='center', echo=FALSE}
# Preparar eixos para os gráficos
fig, eixos = plt.subplots(1, 2, figsize=(30,15));
# Realizar gráficos
sns.lineplot(x='ano', y='Internacional', data=dados_turismo_fluxoGeralSSA, marker='o', ax=eixos[0]);
sns.lineplot(x='ano', y='Doméstico', data=dados_turismo_fluxoGeralSSA, marker='o', ax=eixos[1]);
# Configuracoes do gráfico
eixos[0].set_title('Visitantes Internacionais',fontsize=25,fontweight='bold');
eixos[0].set_xlabel('Ano',fontsize=20);
eixos[0].set_ylabel('Visitantes [milhares]',fontsize=20);
plt.setp(eixos[0].get_xticklabels(),fontsize=15);
plt.setp(eixos[0].get_yticklabels(),fontsize=15);
eixos[1].set_title('Visitantes Nacionais',fontsize=25,fontweight='bold');
eixos[1].set_xlabel('Ano',fontsize=20);
eixos[1].set_ylabel('');
plt.setp(eixos[1].get_xticklabels(), fontsize=15);
plt.setp(eixos[1].get_yticklabels(), fontsize=15);
plt.tight_layout();
plt.show();
```

As séries temporais apresentadas na `fig36` apresentam o fluxo turístico internacional (a esquerda) e nacional (a direita) em Salvador. É possível avaliar através destes gráficos que 2014 apresentou um enorme fluxo tanto nacional quanto internacional em Salvador. Este aumento expressivo identificado em um determinado período em comparação com os demais é chamada de **pico**. A ocorrência de um pico é comumente atrelada a um evento inesperado que pode explicar sua origem. Neste caso em específico, o aumento expressivo de turistas em Salvador pode ser relacionado a Copa do Mundo de 2014, maior evento de futebol do mundo, sediada no Brasil onde alguns jogos aconteceram na capital bahiana. Esse fato é corroborado pela raridade dessa ocorrência (primeira vez que ocorreu) e pela diferença deste período em comparação aos anos anteriores e posteriores a 2014.

Além de avaliar eventos únicos que possam ter ocorrido, buscando compreendê-los, as séries temporais são ferramentas essenciais para acompanhar um determinado processo ou fluxo, podendo auxiliar na tomada de decisões.

``` {python fig37, fig.cap='Fluxo de desembarques e embarques no terminal rodoviário de Salvador em 2019.', out.width='90%', fig.asp=.75, fig.align='center', echo=FALSE}
# Preparar eixos para os gráficos
fig, eixos = plt.subplots(1, 2, figsize=(30,15));
# Realizar gráficos
sns.lineplot(x='mês',y='desembarque',data=dados_turismo_fluxoRodoviariaSSA, marker='o', sort=False, ax=eixos[0], color='red');
sns.lineplot(x='mês',y='embarque',data=dados_turismo_fluxoRodoviariaSSA, marker='o', sort=False,ax=eixos[1]);
# Configuracoes do gráfico
eixos[0].set_title('Desembarques em 2019',fontsize=25,fontweight='bold');
eixos[0].set_xlabel('Mês',fontsize=20);
eixos[0].set_ylabel('Passageiros [milhares]',fontsize=20);
plt.setp(eixos[0].get_xticklabels(), rotation=45, ha="right", rotation_mode="anchor", fontsize=15);
plt.setp(eixos[0].get_yticklabels(), fontsize=15);
eixos[1].set_title('Embarques em 2019',fontsize=25,fontweight='bold');
eixos[1].set_xlabel('Mês',fontsize=20);
eixos[1].set_ylabel('');
plt.setp(eixos[1].get_xticklabels(), rotation=45, ha="right", rotation_mode="anchor", fontsize=15);
plt.setp(eixos[1].get_yticklabels(), fontsize=15);
plt.tight_layout();
plt.show();
```

As informações contidas na Figura `fig37` podem ser interessantes, por exemplo, para um gestor público responsável pelo terminal rodoviário de Salvador que pode identificar:
- durantes os meses de Janeiro, Junho e Dezembro ocorrem os períodos de maiores movimentações tanto para embarque quanto para desembarque. Isso pode indicar a necessidade de mais investimentos/atenção dos funcionários do terminal para garantir a movimentação sem grandes transtornos.
- os meses de Maio e Setembro apresentam o menor movimento. Logo, o investimento neste período pode ser reduzido em detrimento de meses com maiores movimentações como Janeiro e Dezembro.

Ou seja, a compreensão de gráficos deste tipo podem ajudar na tomada de decisões durante o gerenciamento através da compreensão de períodos importantes.

## Histograma
Um histograma de um conjunto de dados numéricos se parece muito com um gráfico de barras apresentado anteriormente, embora tenha algumas diferenças importantes que examinaremos nesta seção. Primeiro, abaixo é apresentado um histograma para mostrar a distribuição da idade dos participantes do ENEM 2018 na cidade de Salvador:


``` {python fig38, fig.cap='Histograma da idade dos participantes do ENEM 2018 na cidade de Salvador', out.width='90%', fig.asp=.75, fig.align='center', echo=FALSE}
# Definir tamanho da figura
plt.figure(figsize=(20,10));

# Realizar grafico
eixo = dados_enem_alunos['NU_IDADE'].hist(bins=10, grid=False,edgecolor='black', linewidth=1.5);
plt.yticks(fontsize=25);
plt.xticks(fontsize=25);
plt.xlabel('Idade', fontsize=30, weight='bold');
plt.ylabel('');
eixo.spines['right'].set_visible(False);
eixo.spines['top'].set_visible(False);
plt.tight_layout();
plt.show();
```

No eixo horizontal está representado os valores numéricos da idade dos participantes do ENEM que foram agrupados em intervalos discretos. Fazendo um paralelo com o \@ref(capitulo-2), o intervalo contínuo numérico estudado foi transformado para **K** valores categóricos/discretos. Este valor **K** é definido pelo usuário e na imagem anterior é definido como igual a 10. Você pode perceber isso ao contar a quantidade de "caixinhas" que existem no histograma. Já o eixo vertical representa a quantidade de valores que estão em cada categoria, ou seja, quanto mais valores são representados por aquela classe maior será a altura de sua barra. Caso você esteja afiado, provavelmente notou uma semelhança com a frequência absoluta apresentada durante a seção \@ref(#graficos-de-barras). 

Ao avaliar um histograma é preciso entender que cada barra representa uma categoria que define um intervalo contínuo limitado. Esse intervalo é na maioria das vezes apresentado da seguinte forma:
$$[limite\ inferior,\ limite\ superior)$$
Onde o $limite\ inferior$ representa o menor valor contido naquela categoria e $limite\ superior$ o maior valor daquela categoria. Porém, na matemática os sinais $[$ e $)$ apresentam um significado específico, importantes para compreender a definição de uma categoria do histograma: o primeiro representa um intervalo fechado já o segundo um intervalo aberto. Juntando todo este conhecimento é possível dizer que cada K categoria em um histograma contém seu limite inferior, mas não contém seu limite superior. Em outras palavras, uma determinada barra (categoria) não representa seu limite superior, logo uma categoria começa no limite inferior e termina no superior, sem inclui-lo.

Na `fig38` é possível observar que com 10 categorias, a medida que aumenta a idade dos participantes mais difícil se torna difícil enxergar as barras. Além disso, a categoria mais dominante se encontra na faixa dos 18 aos 26 anos. Caso seja desejado aumentar a resolução desses intervalos, será necessário realizar o aumento de categorias e isso pode ser conquistado ao aumentar o valor de K.

``` {python fig39, fig.cap='Histograma da idade dos participantes do ENEM 2018 na cidade de Salvador com uma maior resolução', out.width='90%', fig.asp=.75, fig.align='center', echo=FALSE}
# Definir tamanho da figura
plt.figure(figsize=(20,10));

# Realizar grafico
eixo = dados_enem_alunos['NU_IDADE'].hist(bins=25, grid=False,edgecolor='black', linewidth=1.5);
plt.yticks(fontsize=25);
plt.xticks(fontsize=25);
plt.xlabel('Idade', fontsize=30, weight='bold');
plt.ylabel('');
eixo.spines['right'].set_visible(False);
eixo.spines['top'].set_visible(False);
plt.tight_layout();
plt.show();
```

Ao utilizar 25 categorias, como apresentado na `fig39` é possível identificar que o intervalo de idade mais dominante foi anulado para participantes com idade em torno de 15 aos 21 anos, o que é congruente visto que a maioria dos inscritos no ENEM são estudantes do ensino médio. Essa conclusão é corroborada com a queda da no eixo vertical para idades superiores a 20 anos.

Para corroborar ainda mais essa ideia vamos analisar o gráfico abaixo:
``` {python fig310, fig.cap='Histograma da idade dos participantes do ENEM 2018 na cidade de Salvador com uma maior resolução', out.width='90%', fig.asp=.75, fig.align='center', echo=FALSE}
# Gráfico de pizza
labels = ['Abaixo dos 20 anos', 'Acima dos 20 anos']
sizes = [dados_enem_alunos['IDADE_CATEGORICA'].value_counts()[1], dados_enem_alunos['IDADE_CATEGORICA'].value_counts()[0]]
fig1, eixo = plt.subplots()
eixo.pie(sizes, labels=labels, autopct='%1.1f%%', shadow=False)
eixo.axis('equal')
plt.show()
```

O gráfico de pizza exposto na `fig310` avalia a quantidade de estudantes de acordo ao um limite de 20 anos de idade. É verificado que quase 50% dos participantes do ENEM 2018 apresentam uma idade inferior a 20 anos, solidificando ainda o que foi verificado durante a a análise do histograma passado, mesmo com um intervalo de idade que vai desde os 12 anos até 81 anos verificado.

Após concluir a leitura desta seção você pode notar a semelhança entre **histograma** e **gráfico de barras**, porém não confunda: eles são diferentes! Suas principais diferenças são:
- Os gráficos de barras exibem uma quantidade por categoria. Eles são frequentemente usados para exibir as distribuições de variáveis categóricas. Os histogramas exibem as distribuições de variáveis numéricas.
- Todas as barras em um gráfico de barras têm a mesma largura e há uma quantidade igual de espaço entre as barras consecutivas. As barras de um histograma podem ter larguras diferentes e são contíguas.

**Nota**: É importante ressaltar que alguns materiais trazem o conceito da densidade para o eixo vertical, porém dado o direcionamento do livro será mantido uma análise sem abordar este conceito dado a sua complexidade. A ideia de densidade é importante quando é analisado histogramas com intervalos de tamanhos diferentes, mas para intervalos iguais tanto o conceito de frequência absoluta (contagem) quanto densidade funcionam para o mesmo propósito.

## Aprimorando suas visualizações

## Indo Além ...

## Referências
https://pt.wikipedia.org/wiki/Gr%C3%A1fico_de_barras

